In [1]:
import numpy as np

my_array=np.array([[10, 20, 30],[40, 50,60]])
# print(my_array.shape)
# print("number of dimensions",my_array.ndim)
# print("First row:", my_array[0])
# print("last row:", my_array[:,-1])

print("\nShape:", my_array.shape,
      "\nDimensions:", my_array.ndim, 
      "\nFirst row:", my_array[0], 
      "\nLast column:", my_array[:, -1])


Shape: (2, 3) 
Dimensions: 2 
First row: [10 20 30] 
Last column: [30 60]


In [2]:
# my_array = np.array ([1, 2, 3,4, 5, 6,7, 8, 9,10])
# print(my_array)
# my_array2 =np.array([0,0, 0, 0,0])
# print(my_array2)
# final_array= np.ones((3,3))
# print(final_array)

my_array = np.arange (1,11)
print(my_array)
zero_array =np.zeros(5)
print(zero_array)
final_array= np.ones((3,3))
print(final_array)

[ 1  2  3  4  5  6  7  8  9 10]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
my_array=np.array([10, 20, 30, 40, 50])
# #sum
# total_sum=np.sum(my_array)
# print('sum',total_sum)
# #min
# min_value=np.min(my_array)
# print('Mininum',min_value)
# #max
# max_value=np.max(my_array)
# print('maximum',max_value)
# #mean
# mean_value=np.mean(my_array)
# print('Mean',mean_value)
# #multiply
# multiply_value=my_array*2
# print('multiply by 2',multiply_value)
# #add 5 element in each elemet
# new_array= my_array+5
# print('new array add by 5',new_array)

print("Sum:", np.sum(my_array))
print("Min:", np.min(my_array))
print("Max:", np.max(my_array))
print("Mean:", np.mean(my_array))
print("Multiply by 2:", my_array * 2)
print("Add 5:", my_array + 5)


Sum: 150
Min: 10
Max: 50
Mean: 30.0
Multiply by 2: [ 20  40  60  80 100]
Add 5: [15 25 35 45 55]


In [4]:
my_array=np.array([5, 10, 15, 20, 25, 30])

print('first 2 elements',my_array[0:3])
print('last 2 elemets',my_array[-2:])
my_array[2]=100
print(my_array)



# slice = [0, 3, -2,-1] 
# result = my_array[slice]
# print('First  2 and last  2 in single array',result)

first 2 elements [ 5 10 15]
last 2 elemets [25 30]
[  5  10 100  20  25  30]
